import { ContextDataProvider } from "./context"
export const metadata = {
  title: 'Gym App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <ContextDataProvider>
          {children}
        </ContextDataProvider>
      </body>
    </html>
  )
}
